apiVersion: apps/v1
kind: Deployment
metadata:
  name: dspacesolr
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dspacesolr
  template:
    metadata:
      labels:
        app: dspacesolr
    spec:
      containers:
        - name: dspacesolr
          image: dspace/dspace-solr:dspace-9_x
          ports:
            - containerPort: 8983
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /solr/admin/info/system
              port: 8983
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /solr/admin/info/system
              port: 8983
            initialDelaySeconds: 30
            periodSeconds: 10
          workingDir: /var/solr/data
          command: ["/bin/bash", "/scripts/entrypoint.sh"]
          securityContext:
            runAsUser: 0 # Need root to chown and copy
          volumeMounts:
            - name: solr-data
              mountPath: /var/solr/data
            - name: init-script
              mountPath: /scripts
      volumes:
        - name: solr-data
          persistentVolumeClaim:
            claimName: solr-data-pvc
        - name: init-script
          configMap:
            name: solr-init-script
            defaultMode: 0755
