apiVersion: v1
kind: Service
metadata:
  name: dspace-backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 80
      targetPort: 8080
      name: http-alt
    - port: 8000
      targetPort: 8000
      name: debug
  selector:
    app: dspace-backend
