
# Activar el tema 'custom' para la UI
# Cambiado de 'test' a 'custom' para usar el tema personalizado
themes:
  - name: custom

rest:
  ssl: false
  host: localhost
  port: 8080
  nameSpace: /server
