apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Common Resources
  - common/secrets.yaml
  - common/custom-headers.yaml
  - common/ingress.yaml

  # Database (PostgreSQL)
  - postgres/pvc.yaml
  - postgres/service.yaml
  - postgres/deployment.yaml

  # Search Engine (Solr)
  - solr/pvc.yaml
  - solr/configmap.yaml
  - solr/service.yaml
  - solr/deployment.yaml

  # Backend (DSpace API)
  - backend/pvc.yaml
  - backend/configmap.yaml
  - backend/sitemap-cronjob.yaml
  - backend/service.yaml
  - backend/deployment.yaml

  # Frontend (DSpace Angular)
  - frontend/configmap.yaml
  - frontend/service.yaml
  - frontend/deployment.yaml